### ISSUE TITLE
Got no valid response from konnektor

### ISSUE THREAD

**Issue by konnektor3000** [Kleinrotti/checkmk_telematik#3]
Hello,

thanks for this plugin. Is this agent supposed to work with connectors of all manufacturers and types?

I receive the following error message:
```
OMD[xyz]:~$ /omd/sites/xyz/local/share/check_mk/agents/special/agent_telematik_konnektor '-u' '123.456.789.012' '-p' 123 '-m' 'xyz' '-c' 'xyz' '-w' 'xyz'
Got no valid response from konnektor.Code: 404 Message:
Got no valid response from konnektor.Code: 404 Message:
Got no valid response from konnektor.Code: 404 Message:
Parsing cards failed. ('no element found: line 1, column 0',)
Traceback (most recent call last):
  File "/omd/sites/xyz/local/share/check_mk/agents/special/agent_telematik_konnektor", line 470, in <module>
    main(args)
  File "/omd/sites/xyz/local/share/check_mk/agents/special/agent_telematik_konnektor", line 436, in main
    for card in cards:
UnboundLocalError: local variable 'cards' referenced before assignment
```

I’d appreciate any advice for further trouble shooting.

**Comment by Kleinrotti** [comment]
All manufactures have to use the same specifications from Gematik, so all Manufactures should would. I could only test it with Secunet which works.
Keep in mind that remote monitoring needs to be enabled in the Konnektor.
It is also possible that the Konnektor has [client authentication](https://github.com/Kleinrotti/checkmk_telematik/issues/1#issuecomment-1569726690) enabled, which requires the use of a client certificate which is not yet implemented in the plugin but will be in the next release.

**Comment by konnektor3000** [comment]
I’m struggling with a KoCoBox MED+ Version 5. In its manual I can’t find a setting like remote monitoring. For testing on a standby connector mandatory client authentication is disabled. When client authentication is set to required it fails with “Couldn't establish a connection to the konnektor. (MaxRetryError("HTTPSConnectionPool(host='123.456.789.012', port=1234): Max retries exceeded with url: /ws/CardService (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_BAD_CERTIFICATE] sslv3 alert bad certificate”. I will try again with client certificate authentication with the next release.

Could I manually test the Konnektor’s behaviour with a curl command or browser?

**Comment by Kleinrotti** [comment]
You can use something like Postman to make a post request for testing.
Here is a sample request to get all cards (insert your mandant id, clientsystem id and workplace id in the xml)
`<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
    <SOAP-ENV:Header/>
    <SOAP-ENV:Body>
        <ns4:GetCards xmlns:ns2="http://ws.gematik.de/conn/ConnectorCommon/v5.0" xmlns:ns3="http://ws.gematik.de/tel/error/v2.0" xmlns:ns4="http://ws.gematik.de/conn/EventService/v7.2" xmlns:ns5="http://ws.gematik.de/conn/CardServiceCommon/v2.0" xmlns:ns6="http://ws.gematik.de/conn/CardService/v8.1" xmlns:ns7="http://ws.gematik.de/conn/ConnectorContext/v2.0" xmlns:ns8="http://ws.gematik.de/int/version/ProductInformation/v1.1" xmlns:ns9="http://ws.gematik.de/conn/CardTerminalInfo/v8.0">
            <ns7:Context>
                <ns2:MandantId></ns2:MandantId>
                <ns2:ClientSystemId></ns2:ClientSystemId>
                <ns2:WorkplaceId></ns2:WorkplaceId>
            </ns7:Context>
        </ns4:GetCards>
    </SOAP-ENV:Body>
</SOAP-ENV:Envelope>`

**Comment by Kleinrotti** [comment]
I have checked the Gematik specifications again and I found that the Konnektor have not the explicit requirement to support Remote Monitoring.
![image](https://github.com/Kleinrotti/checkmk_telematik/assets/39203164/3c984f80-2e2f-435b-b9ab-8a8040dae1fd)
[Source](https://fachportal.gematik.de/fachportal-import/files/gemSpec_Kon_V5.13.0.pdf)

You should get more information if you test the requests with Postman as I wrote before.

**Comment by konnektor3000** [comment]
I added workplace id, mandant id and clientsystem id to the soap example that you provided. As I’m not used to postman I put it into a file “test2.xml” and used curl.

This did not return a result:
`curl --header "Content-Type: text/xml;charset=UTF-8" --data @test2.xml https://123.456.789.012:1234 -k`

Then I added /service/systeminformationservice to the url:
`curl --header "Content-Type: text/xml;charset=UTF-8" --data @test2.xml https://123.456.789.012:1234/service/systeminformationservice -k`

and got a good looking result which contained actual information about cards:
`<?xml version="1.0" ?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><ns11:GetCardsResponse […]`

For a quick test I replaced /ws/CardService in agent_telematik_konnektor with /service/systeminformationservice and received:
`Got no valid response from konnektor.Code: 500 Message: <?xml version="1.0" ?> … Es ist nur das Character-Encoding "UTF-8" erlaubt.`
I intend to ask the manufacturer about remote monitoring and compatibility.

**Comment by bad13** [comment]
Same here... but some other errors...

Got no valid response from konnektor.Code: 404 Message:
Got no valid response from konnektor.Code: 404 Message:
Got no valid response from konnektor.Code: 404 Message:
Traceback (most recent call last):
  File "/opt/omd/sites/mysite/local/share/check_mk/agents/special/./agent_telematik_konnektor", line 482, in <module>
    main(args)
  File "/opt/omd/sites/mysite/local/share/check_mk/agents/special/./agent_telematik_konnektor", line 440, in main
    cards = parseCards(cardResponse.text)
  File "/opt/omd/sites/mysite/local/share/check_mk/agents/special/./agent_telematik_konnektor", line 311, in parseCards
    tree = ET.ElementTree(ET.fromstring(xmlString))
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1343, in XML
    return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

**Comment by Kleinrotti** [comment]
Please try this to debug with Postman-> https://github.com/Kleinrotti/checkmk_telematik/issues/3#issuecomment-1582853717

**Comment by Kleinrotti** [comment]
Maybe the public or private key has the wrong format. Unfortunately I can't test client authentication, because we don't use it in our environment.
I have implemented it as in the [documentation](https://docs.python-requests.org/en/latest/user/advanced/#client-side-certificates) of the requests module.

You can also use the --debug flag in the terminal to execute the special agent with more debugging information.

**Comment by Kleinrotti** [comment]
Thanks for your hint :) I forgot to append the client certificate there.
I will do a quick hotfix.

**Comment by konnektor3000** [comment]
Thanks for your quick fix.

I made the agent work with KoCoBox MED+ Version 5 now. I had to enable “Mandant-wide request” in the “Telematikinfrastruktur Konnektor Agent“ rule to make the queries work with my chosen workplace id and the following two changes in code were necessary:


- Replace all occurrences of /ws/CardService with /service/systeminformationservice

- In function "request" change
`response = requests.post(url, headers={"Content-Type": "text/xml"}, data=data, verify=verify_ssl, cert=client_cert)`
to
`response = requests.post(url, headers={"Content-Type": "text/xml;charset=UTF-8"}, data=data, verify=verify_ssl, cert=client_cert)`

I assume the change of url won’t be compatible with Secunet connectors. I’d suggest to add a parameter or some kind of auto discovery functionality.

One problem remains:
Got no response from Konnektor. Calling function: requestPinStatus, HTTP code: 500
`<faultstring>Cannot find dispatch method for {http://ws.gematik.de/conn/CardService/v8.1}GetPinStatus</faultstring>`
For now, I commented out the call of requestPinStatus.

**Comment by Kleinrotti** [comment]
I will check if your additional changes are compatible with a Secunet Konnektor.

**Comment by Kleinrotti** [comment]
Could you provide the connector.sds xml from the KocoBox?
Then I can compare it with the connector.sds from secunet and program a dynamically parsed url based on the Konnektor.

**Comment by konnektor3000** [comment]
Do you mean `requests.get(f"https://{host}:{port}/connector.sds", verify=verify_ssl, cert=client_cert).text`? I attached the output: [connector.sds.xml.txt](https://github.com/Kleinrotti/checkmk_telematik/files/13320723/connector.sds.xml.txt).

**Comment by Kleinrotti** [comment]
Yes thanks :) I will create a test release in the next few days with automatic detection, it would be nice if you could test it then :)

**Comment by michikmm** [comment]
Hello,
same for me - @konnektor3000 your suggested changes working for me. Little additional change:

- Replace all occurrences of /ws/CardTerminalService with /service/systeminformationservice

We are using a few KoCoBox MED+ Version 5.1.6, Hardware 2.0.0, 
[connector.sds.xml.txt](https://github.com/Kleinrotti/checkmk_telematik/files/13828593/connector.sds.xml.txt)

We are also happy to test it :-)

**Comment by Kleinrotti** [comment]
Sorry for my late response, my time was a bit limited in the last few weeks due to work on other projects.
Nice to hear that these changes work with a KoCoBox. Could you test if even the url /service is enough?
I have tested on our Secunet Konnektor that only /ws is enough to get a valid response. Seems like everything behind that is ignored for that kind of requests. Would be nice to know :)

**Comment by michikmm** [comment]
url /service is not enough - 404 no valid response.
For KocoBox it seems to be full /service/systeminformationservice

**Comment by michikmm** [comment]
Hello Kleinrotti,
maybe any news on this? :-)
We have new KoCoBox'es, here connector.sds for Version 5.1.10, Hardware 4.0.0
[connector.sds.txt](https://github.com/Kleinrotti/checkmk_telematik/files/14447937/connector.sds.txt)

**Comment by michikmm** [comment]
Hi Kleinrotti,
i removed version 1.2.0 and all rules, installed 1.3 and recreated rules. I had to deactivate the pin because of reqestPinStatus 500, this is working.

**Comment by Kleinrotti** [comment]
Thanks for the feedback :)
Could you also try this version and check if the pin request works there?
Sorry for the hassle but unfortunately I have no Kocobox to test this by myself.
[telematik_konnektor-1.3.1.mkp.zip](https://github.com/Kleinrotti/checkmk_telematik/files/14514381/telematik_konnektor-1.3.1.mkp.zip)

**Comment by michikmm** [comment]
Pin Status is working, great job 👌
An other thing that i have just noticed: Flag mandant-wide seems not to work. In our TI deployment we're using more than 10 mandants per connector. 
If mandant-wide is selected, it returns only SMC-Bs of given mandant and not of all mandants from connector. It seems to change nothing

**Comment by Kleinrotti** [comment]
Happy to hear that it works now :)

Manadant-wide has another meaning. It returns not only the cards of the remote card terminal, it returns all cards and terminals which are associated to that mandant.

>  Darüber hinausgehend kann 
mittels des Attributs mandant-wide="true" eine Abfrage initiiert werden, die die 
Kartenobjekte für sämtliche gesteckte Karten zurückliefert, die sich in allen dem 
Mandanten zugeordneten Kartenterminals befinden.

[Source, Page 47](https://fachportal.gematik.de/fileadmin/Fachportal/Downloadcenter/Implementierungsleitfaeden/gemILF_PS_V2.7.0.pdf)

If you want to request multiple mandants on the same Konnektor, you have to create a new rule and a new host.

**Comment by Kleinrotti** [comment]
Fixed by #10

**Comment by konnektor3000** [comment]
Hello,

today I tried out telematik_konnektor 1.3.1 with our KoCoBox MED+ connectors. The agent still fails with HTTP 500 error from requestPinStatus.
While debugging I noticed that for some SMC-B the PIN status is retrieved successfully. But for at least one SMC-B pin status request fails with error message:
`<ns4:ErrorText>SM-B_Verwaltet ist dem Mandanten nicht zugeordnet</ns4:ErrorText>`
May it make sense to add some code to handle this situation?

**Comment by Kleinrotti** [comment]
Something with the configuration is not ok then.
If your card goes to critical in checkmk, its handled right.

**Comment by konnektor3000** [comment]
At the moment the "Mandant" used to run the check is unable to request PIN status of all SMC-Bs in our organizations. I will discuss the constellation with my colleague.

Besides that in the current situation no services are discovered at all. Therefore, I did some quick and dirty modifications.

To make the agent continue after an HTTP 500 error and to discover services I removed `if response.status_code != 200:` block from function requests and removed `checkErrors(pinResponse)` from loop "card in cards" in function main.

To stop services "Card SMC-B…" from crashing I added
`if child.tag == "{http://ws.gematik.de/tel/error/v2.0}Error":
            return '-'`
to function parsePIN to get status '-' in case of `<ns4:ErrorText>SM-B_Verwaltet ist dem Mandanten nicht zugeordnet</ns4:ErrorText>`.
